41 data pipeline skeleton
VIP-LES/EosGround pull request #45
Opened 2023-02-27 23:41 UTC by DarylDohner

2023-02-27 23:46 UTC, DarylDohner commented
(forgot to add the dummy tables to the sql files, will do soon)

2023-02-28 10:42 UTC, DarylDohner commented
(forgot to add the dummy tables to the sql files, will do soon)
^ actually I think this is not the case, I think this ticket may technically be blocked by #24 @David-Rey

2023-03-04 19:15 UTC, DarylDohner commented on EosGround/database/db_setup.py
> +def configure_db():
Not sure why github isn't rendering the diff but the only changes I made were moving the file, making filepaths cross-platform, adding some print statements, and adding the test_schema setup

2023-03-11 02:38 UTC, thomasmholder requested changes
Looks pretty good, but I think you should add an example foreign key relationship to the test schemas, I got one working but getting the name right in the model was a little fiddly, and pretty much every pipeline is going to have a foreign key relationship.

2023-03-11 17:42 UTC, thomasmholder requested changes
Looks good and works on my end, just one thing with the dependencies

2023-03-11 17:42 UTC, thomasmholder commented on requirements.txt
> +psycopg2==2.9.5
We should use either `psycopg2` or `psycopg2-binary`, I see having both in our dependencies causing issues

2023-03-11 17:42 UTC, thomasmholder commented on requirements.txt
> +psycopg2==2.9.5
(My vote is for `psycopg2-binary` but I can figure out how to build the other one if I have to)

2023-03-12 21:11 UTC, thomasmholder approved these changes

2023-03-12 21:11 UTC, thomasmholder commented
Lgtm

2023-03-12 21:12 UTC, merged