66 terminal output pipeline
VIP-LES/EosGround pull request #69
Opened 2023-10-25 03:54 UTC by aryanbattula

created the terminal output pipeline

2023-11-02 19:12 UTC, VanL15 requested changes
See comments, only a few things to change. Also, if you disagree with any of the changes let me know.

2023-11-02 19:12 UTC, VanL15 commented on EosGround/database/pipeline/pipelines/terminal_output_pipeline.py
> +        packet_body = CutDown.decode(record.packet_body)
Same here with `CutDown.decode`.

2023-11-02 19:36 UTC, aryanbattula commented on EosGround/database/models/eos/transmit.py
> +    generate_time: Mapped[int] = mapped_column()
good catch

2023-11-07 03:51 UTC, IonLi09 approved these changes
pipeline was tested on my laptop. lgtm!

2023-11-07 03:58 UTC, merged